coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch: false

ignore:
  - "Riot"
  - "RiotSwiftUI/Modules/AnalyticsPrompt"
  - "RiotSwiftUI/Modules/Authentication"
  - "RiotSwiftUI/Modules/Common"
  - "RiotSwiftUI/Modules/LocationSharing"
  - "RiotSwiftUI/Modules/Onboarding"
  - "RiotSwiftUI/Modules/Room"
  - "RiotSwiftUI/Modules/Settings"
  - "RiotSwiftUI/Modules/Spaces"
  - "RiotSwiftUI/Modules/Template"  

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
