name: Riot
attributes:
  ORGANIZATIONNAME: matrix.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.md
    - AUTHORS.rst
    - Podfile
    - project.yml
    - changelog.d

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh
    
include:
  - path: Riot/target.yml
  - path: RiotTests/target.yml
  - path: RiotShareExtension/target.yml
  - path: SiriIntents/target.yml
  - path: RiotNSE/target.yml
  - path: DesignKit/target.yml
  - path: RiotSwiftUI/target.yml
  - path: RiotSwiftUI/targetUnitTests.yml
  - path: RiotSwiftUI/targetUITests.yml
  - path: CommonKit/target.yml
  - path: CommonKit/targetUnitTests.yml

packages:
  Mapbox:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    minVersion: 5.12.2
    maxVersion: 5.13.0
  OrderedCollections:
    url: https://github.com/apple/swift-collections
    minVersion: 1.0.2
    maxVersion: 2.0.0
  SwiftOGG:
    url: https://github.com/vector-im/swift-ogg
    branch: main
