blank_issues_enabled: true
contact_links:
  - name: Enhancement or feature request
    url: https://github.com/vector-im/element-meta/discussions/categories/ideas
    about: Do you have a suggestion or feature request?
  - name: Element iOS Community Support
    url: https://matrix.to/#/#element-ios:matrix.org
    about: General Element iOS support questions can be asked in the app Matrix room
