# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "matrixConsole" do

# Points to SDK local sources file
pod 'MatrixKit', :path => '../../../matrix-ios-kit/MatrixKit.podspec'
pod 'MatrixSDK', :path => '../../MatrixSDK.podspec'
pod 'libPhoneNumber-iOS', '~> 0.7.6'
pod 'GBDeviceInfo', '~> 2.2.9'
end

target "matrixConsole" do

end

