# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "syMessaging" do

# Points to SDK local sources file
pod 'MatrixSDK', :path => '../../MatrixSDK.podspec'

end

target "syMessagingTests" do

end

